# Generated by Django 4.1 on 2024-03-02 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                ("hostel_id", models.AutoField(primary_key=True, serialize=False)),
                ("hostel_name", models.CharField(max_length=100)),
                ("rooms_available", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("admin_id", models.AutoField(primary_key=True, serialize=False)),
                ("admin_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="administrator",
            fields=[
                ("a_id", models.AutoField(primary_key=True, serialize=False)),
                ("a_name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="College",
            fields=[
                ("CID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Location", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                ("EID", models.IntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=50)),
                ("EDate", models.DateField()),
                ("Type", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=1000, null=True)),
                ("venue", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Participants",
            fields=[
                ("PID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                (
                    "CID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.college"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("Roll", models.IntegerField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                ("VID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "EID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.event"
                    ),
                ),
                (
                    "Roll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.event"
                    ),
                ),
                (
                    "roll_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.student"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organizer",
            fields=[
                ("org_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Winner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(choices=[(1, "1st"), (2, "2nd"), (3, "3rd")]),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.event"
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.participants",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "position")},
            },
        ),
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "EID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.event"
                    ),
                ),
                (
                    "PID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.participants",
                    ),
                ),
            ],
            options={
                "unique_together": {("EID", "PID")},
            },
        ),
    ]
